<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>

<body class="for-home" style="overflow-y: visible;">

    <main class="text-white">
        <section class="section-1">
            <img src="<?= base_url();?>assets/media/images/home-cover-img.png" alt="" class="img-fluid">
            <div class="content">
                <h1 class="cover-heading hvc-reg--ff text-uppercase text-white text-center">Terms & Conditions</h1>
            </div>
        </section>

        <div class="container">
            <div>
                <h2 class="my-5">Introduction</h2>
                <p>The terms and conditions written in this website shall control your use of our website. These terms may be applied genuinely and affect your use of this website. By the way of using this website, you agreed to accept all the terms and conditions written here. You need to no longer use this website in case you disagree with any of these internet website terms and conditions.</p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Intellectual Property Rights</h2>
                <p>Other than your personal content material, this internet website contains FashionTV India LTD and/or its licensors very personal all of the intellectual property rights below these terms and conditions. You're granted a confined license just for functions of viewing the substances contained on this internet site.</p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Restrictions</h2>
                <ul>
                    <p>Publishing any internet site material in another media.</p>
                    <p>Promoting, sublicensing and/or in any other case commercializing any website fabric.</p>
                    <p>Publicly appearing and/or showing any website materials.</p>
                    <p>Using this internet site in any way that may be destructive to this internet site.</p>
                    <p>The use of this website in any manner that affects person get admission to this website.</p>
                    <p>The usage of this website contrary to applicable legal guidelines and policies, or in any manner may additionally cause damage to the internet site, or to any individual or enterprise entity.</p>
                    <p>
                        Accomplishing any facts mining, data harvesting, data extracting or
                        any other activity in terms of this internet site.
                    </p>
                    <p>
                        Using the internet site to have interaction in any marketing or
                        advertising.
                    </p>
                </ul>
                <br />
                <p>
                    Some regions of this website are confined from being accessed by you
                    and FashionTV India LTD can also similarly limit access by using you
                    to any regions of this internet site, at any time, in absolute
                    discretion. Any identification and password you may have for this
                    internet site are confidential and you must keep it confidential.
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Your Content</h2>
                <p>
                    “Your content” can be any audio, video, text content, images or
                    different material you select to display on this website. You grant a
                    non-exclusive, international irrevocable, sub-licensable license to
                    apply, reproduce, adapt, publish, translate and distribute it in any
                    and all media by means of displaying your content material on
                    FashionTV India LTD.
                </p>
                <br />
                <p>
                    Your content material has to be generated by your own and should not
                    be invading any third party's rights. FashionTV India LTD reserves the
                    proper right to remove any of your content from their website at any
                    time without any notice.
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">No Warranties</h2>
                <p>
                    FashionTV India LTD provides no representations or warranties, of any
                    type related to this internet site or the materials contained on this
                    website. additionally, nothing contained on this internet site shall
                    be explained as advising you
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Limitation of liability</h2>
                <p>
                    FashionTV India LTD provides no representations or warranties, of any
                    type related to this internet site or the materials contained on this
                    website. additionally, nothing contained on this internet site shall
                    be explained as advising you
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Indemnification</h2>
                <p>
                    You hereby compensate to the fullest extent FashionTV India LTD from
                    and in opposition to any and/or all liabilities, prices, needs,
                    reasons of movement, damages and expenses arising in any way
                    associated with your breach of any of the provisions of these terms.
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Severability</h2>
                <p>
                    If any provision of these terms is determined to be invalid underneath
                    any relevant regulation, such provisions will be deleted without
                    affecting the other provisions herein.
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Variation of Terms</h2>
                <p>
                    By using this website you are supposed to review these Terms on a
                    regular basis because FashionTV India LTD is allowed to revise these
                    Terms at any time as it sees fit.
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Assignment</h2>
                <p>
                    You are not permitted to assign, transfer, or subcontract any of your
                    rights and/or obligations under these terms. But the company name is
                    allowed to assign, transfer, and subcontract its rights and/or
                    obligations without any notification.
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Entire Agreemen</h2>
                <p>
                    These terms represent the whole agreement between FashionTV India LTD
                    and you in terms of your use of this internet site and supersede all
                    prior agreements and understandings.
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Governing Law & Jurisdiction</h2>
                <p>
                    These terms will be governed by the legal guidelines of The Mumbai
                    Jurisdiction. You post to the non-exclusive jurisdiction of the state
                    and federal courts placed in the country for the resolution of any
                    disputes.
                </p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Contact Us</h2>
                <p>
                    If you have any queries about these Terms and Conditions, please
                    contact us.
                </p>
                <p><strong>info@fashiontvindia.in</strong></p>
            </div>
            <!--  -->
            <div>
                <h2 class="my-5">Press</h2>
                <p>
                    We are adored by our purchasers and cherished by everyone. Our
                    top-notch brand experience never fails to satisfy our consumers hence
                    FTV is always in the spotlight of media coverage. We are recognised
                    and honoured by various media in India.
                </p>
            </div>
            <!--  -->
        </div>
        <!--  -->
    </main>
    
    <script>
        console.log("Brand License by FashionTV");
    </script>